name: Update Executive Orders RSS Feed

on:
  schedule:
    - cron: "0 * * * *"  # runs hourly — adjust as needed
  workflow_dispatch:  # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run feed generator
        run: python generate_feed.py

      - name: Commit and push updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add executive_orders.xml
          git commit -m "📰 Update RSS feed" || echo "No changes to commit"
          git push
